### ISSUE TITLE
is this a general purpose library?

### ISSUE THREAD

**Issue by Pomax** [jublonet/codebird-js#131]
from the README it looks like this is supposed to be a general purpose library, but when I run it it tries to call jublonet, which suggests that either it's not, or it is but it phones home, which means this isn't secure.

**Comment by jublo** [comment]
## API calls and the same-origin policy

Normally, browsers only allow requests being sent to addresses that are on the same base domain.  This is a security feature called the “same-origin policy.”  However, this policy is in your way when you try to access the (remote) Twitter API domain and its methods.

### Cross-domain requests

With Codebird, don’t worry about this.  We automatically send cross-domain requests using a secured proxy that sends back the required headers to the user’s browser.

This CORS proxy is using an encrypted SSL connection.
*We do not record data sent to or from the Twitter API.
Using Codebird’s CORS proxy is subject to the Acceptable use policy.*

If your JavaScript environment is not restricted under the same-origin policy (for example in node.js), direct connections to the Twitter API are established automatically, instead of contacting the CORS proxy.

You may also turn off the CORS compatibility manually like this:

```javascript
cb.setUseProxy(false);
```

### Support for Internet Explorer 7 to 9

Cross-domain requests work well in any browser except for Internet Explorer 7-9.  Codebird cannot send POST requests in these browsers. For IE7-9, Codebird works in limited operation mode:

- Calls to GET methods work fine,
- calling POST methods is impossible,
- Application-only auth does not work.

### Using your own proxy server

The source code of the CORS proxy is publicly available.  If you want to, set up your own instance on your server.  Afterwards, tell Codebird the address:

```javascript
cb.setProxy("https://example.com/codebird-cors-proxy/");
```

Heads up!  Follow the notes in the [codebird-cors-proxy README](https://github.com/jublonet/codebird-cors-proxy/#readme) for details.

**Comment by Pomax** [comment]
I'm... not sure how to interpret this reply? If this is text you want me to read, then the best rule of thumb is "don't answer people. Write the answer in the readme, and tell people where in the readme you answered their question" so that you don't waste time writing answers twice, and the information isn't lost simply because it was a comment in an issue, which no one will be able to find every again once the issue is closed.

**Comment by jublo** [comment]
@Pomax Thank you for your reply. In fact the answer I had posted as from the easily accessible README file you mentioned. Find the original here: https://github.com/jublonet/codebird-js#api-calls-and-the-same-origin-policy

In short, the Twitter API cannot be accessed directly due to security measures implemented in browsers, and Twitter does not set the required headers to their replies to allow access to their API from third-party JavaScript. Hence, for browser usage of codebird-js, we send the requests to our proxy (find the source code [here](https://github.com/jublonet/codebird-cors-proxy)), which forwards them to the Twitter API, circumventing the direct access problem.

Does this help you?

**Comment by joshuaatkins** [comment]
The answer to your question, is yes it is general use. But as stated in the readme, twitter does not support CORS requests. As a result, this library proxies requests securely though our servers. However, we also have released the code that runs our proxy to vet and host your own proxy. 

The purpose of the proxy is to implement the CORS headers as a middle man.

Although, we appreciate your sass.

**Comment by Pomax** [comment]
no sass intended, just genuine confusion =)
