### ISSUE TITLE
pin Authentication reply httpstatus= 0

### ISSUE THREAD

**Issue by rdaqnha** [jublonet/codebird-js#91]
When I call to oauth_accessToken sending the pincode, I received  httpstatus= 0 and I can't setToken with the oauth_token.
You can see the example in http://rdaqnha.vservers.es/twitter_pin_box.html
I think that all is ok, but I don't know why I don't receive  the oauth_token in the reply.
My app config is 
Website *
http://rdaqnha.vservers.es/twitter_pin_box.html
Callback URL 
http://rdaqnha.vservers.es/twitter_pin_box.html
thanks in advance

**Comment by mrbellek** [comment]
I have the same problem, it seems to be related to issue #92.

**Comment by jublo** [comment]
Has this been resolved for you, @rdaqnha and @mrbellek?

**Comment by mrbellek** [comment]
No. The request_token call to api.jublo.net/codebird/oauth still returns nothing.

**Comment by mrbellek** [comment]
This is what shows in Opera console when I start the 'auth by PIN' example code:

![image](https://cloud.githubusercontent.com/assets/1481377/6959356/6a215cfe-d918-11e4-8d5a-474a9cb2cf21.png)

I put "alert(auth_url);" right after the "function (auth_url) {" line from the example code and it always shows the api.twitter.com link without a token at the end.

**Comment by jublo** [comment]
@mrbellek Please provide us with a staging environment where we can reproduce the issue live. You may send the login details to :email: support@jublo.net and we will keep them secret :lock:.

**Comment by mrbellek** [comment]
Thanks, will try. Hopefully I will have time soon.

**Comment by mrbellek** [comment]
I have setup a test page and sent you an email at the provided email address.

**Comment by jublo** [comment]
Hi Marijn,
Thank you for your patience and the test environment. We could reproduce the issue.

The Codebird authentication code is run in a click handler for a hyperlink element. Browsers do not allow to run calls to servers (Ajax) while a click handler is being processed, because the user will soon navigate away from the page.

The solution is to change your JavaScript onclick handler as follows:

```
$(function() {

    $('#auth').click(function(e) {
        e.preventDefault();

        var cb = new Codebird;
// ...
```

This results in the tokens going through correctly:

![bildschirmfoto 2015-04-18 um 12 15 40](https://cloud.githubusercontent.com/assets/6348321/7215033/f95e637c-e5c4-11e4-9a1a-26986ee25f08.png)

![bildschirmfoto 2015-04-18 um 12 11 28](https://cloud.githubusercontent.com/assets/6348321/7215035/04dad686-e5c5-11e4-88eb-61a4b3b3aa8b.png)

**Comment by jublo** [comment]
Added a README comment in 6d27679d99bd5ba9e1df6b5f88be3d131ae3749c.
