### ISSUE TITLE
Code Bird NOT retrieving tweets

### ISSUE THREAD

**Issue by writeosahon** [jublonet/codebird-js#93]
@jublo Please just noticed that my server app based on CodeBird stopped retrieving new Tweets from my organisations twitter account. It stopped yesterday (Saturday).
Please, I know this is weekend but can someone look into this.
A lot of developers (including myself) rely on CodeBird a lot and I wouldn't mind paying something small to ensure your servers do not misbehave.
Please @jublo . Look into the problem. 
Thanks so much

**Comment by joshuaatkins** [comment]
Hi @writeosahon, Thank you for reporting this to us! We managed to bring the service backup, and have made some additional tweaks to the API infrastructure. 

In terms of your proposal for a paid solution, this is definately something we are considering putting into our business model - but because we like to try and be fair to our users we would like your input first. 

Could you answer some of the following questions?
- How much would you be willing to pay for the service? 
- What payment model would you prefer? (Pay as you go, tiered etc) 
- Would you expect a geographically distributed server cluster? 
- How can we stop people utilising your paid resource? (Using referrers maybe?) 
- What SLA would you expect? 

Obviously, there are more internal considerations for implementation methods, but we are happy to hear what your thoughts are. 

Thanks, 

Josh

**Comment by writeosahon** [comment]
@joshuaatkins Hello. Thanks for responding and fixing the problem.
In answer to your question, I believe the CodeBird library is critical and important to a lot of developers.
* How much will I be willing to pay - I think $10/month (For Application Tokens) and $15/month (For Client/User Tokens)
* Payment Model - I personally prefer a tiered model. It's simpler to understand and calculate. A Free tier should be maintained in the spirit of the OSS Community. However, the premium service should exist for paid customers providing approximately zero proxy server downtime and quick tech support response.
* Would you expect a geographically distributed Server Cluster - In server configuration would be fine. As long as it works (i.e. ~ 0 downtime), and is fast (i.e. server execution speed and response time).
* How to Stop people using your paid resources - Easiest way to prevent this would be a form of domain whitelisting. Users of the library would be expected to register every application using the library on your website Admin Console. Each application would have a unique application key. Also each application MUST provide a list of domains (1 or more) which your proxy server will accept requests from. It may not be an actual domain, However it must be in a valid domain format (e,g. myapp.user.com). The whitelisted domain and the key must be provided when setting up the library properties e.g. codeBird.setAppKey(uniqueKey, whitelistedDomain). This type of protection should be provided for all tiers of users.
* What SLA would you expect - A guarantee that the code works as advertised, contains no malware or spyware. That your proxy server DOES NOT store end-users (twitter users) personal details in any form without first informing the developers using the library (and if such cases exist, developers MUST inform the end-users of the software), that tech support will respond to inquiries/queries between 24 - 48 hrs.

Hope this helps.
PS: Your free proxy server works very well. You guys are doing a great job. Thanks for providing the CodeBird Library and the proxy server service.

**Comment by writeosahon** [comment]
I forgot to add that your paid method MUST support card payments e.g. MasterCard, Visa Card etc.

Cheers!!

**Comment by mohan-mon** [comment]
Hi,
I'm unable to get tweets or connect to your proxy, after seeing this issue i thought you have already started working on it but found your comment "managed to bring the service backup". so thought of informing that it is still giving connection timeout errors.Hope you will look into it.

Thank you in advance,
Mohan.

**Comment by jublo** [comment]
Does this work for you now, @mohan-mon?

**Comment by mohan-mon** [comment]
Yes @jublo , thank you for the efforts put into it.

**Comment by jublo** [comment]
Thanks for your positive feedback!
